### ISSUE TITLE
Not Found - "c:/Users/cloudmax.tech/key.jks"

### ISSUE THREAD

**Issue by bhavneet0812** [AjjuSingh/TrueSDK#1]
Hi, 

First of all a big thanks to you.

I was really looking for this. Since I was an iOS developer that's why it was not easy for me to build the Android part. So thank you so much.

Please let me know when it will be completed.

ERROR -

* What went wrong:
A problem occurred evaluating project ':app'.
> Cannot convert URL 'c:/Users/cloudmax.tech/key.jks' to a file.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 837ms
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by iamc1oud** [comment]
Use below link to follow for android.
[https://docs.truecaller.com/truecaller-sdk/android/generating-app-key](url)
